intro: We offer a wide variety of services for small and medium businesess.
heroImage: /blog-placeholder-about.jpg
details: Here is some great text - lorum ipsum hallujah peanut butter. Here is
  some more!
